/******************************************************************************
 * Filename:       env_service.h
 *
 * Description:    This file contains the LED_Service service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.0.2093.0
 *                 Plugin:      Texas Instruments CC26xx BLE SDK v2.1 GATT Server plugin 1.0.5 beta
 *                 Time:        Tue Jan 26 2016 22:57:47 GMT+01:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef _ENV_SERVICE_H_
#define _ENV_SERVICE_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include <bcomdef.h>

/*********************************************************************
 * CONSTANTS
 */
// Service UUID
#define ENV_SERVICE_SERV_UUID 0x1150
#define ENV_SERVICE_SERV_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0

// Env service command and value. (Command's single character followed by a comma then the value)
#define ES_COMMAND_ID                 0
#define ES_COMMAND_UUID               0x1151
#define ES_COMMAND_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define ES_COMMAND_LEN                20
#define ES_COMMAND_LEN_MIN            1

// Env Service result
#define ES_RESULT_ID                 1
#define ES_RESULT_UUID               0x1152
#define ES_RESULT_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define ES_RESULT_LEN                20
#define ES_RESULT_LEN_MIN            1



//Due to memory issues the method above to define UUIDs had to be implemented instead of the commented out method below

/*
// Max temp Characteristic defines
#define LS_MINTEMP_ID                 0
#define LS_MINTEMP_UUID               0x1151
#define LS_MINTEMP_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MINTEMP_LEN                3
#define LS_MINTEMP_LEN_MIN            1

// Max temp Characteristic defines
#define LS_MAXTEMP_ID                 1
#define LS_MAXTEMP_UUID               0x1152
#define LS_MAXTEMP_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MAXTEMP_LEN                3
#define LS_MAXTEMP_LEN_MIN            1

// Max pressure Characteristic defines
#define LS_MINPRESS_ID                 2
#define LS_MINPRESS_UUID               0x1153
#define LS_MINPRESS_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MINPRESS_LEN                3
#define LS_MINPRESS_LEN_MIN            1

// Max pressure Characteristic defines
#define LS_MAXPRESS_ID                 3
#define LS_MAXPRESS_UUID               0x1154
#define LS_MAXPRESS_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MAXPRESS_LEN                3
#define LS_MAXPRESS_LEN_MIN            1

// Max humidity Characteristic defines
#define LS_MINHUM_ID                 4
#define LS_MINHUM_UUID               0x1155
#define LS_MINHUM_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MINHUM_LEN                3
#define LS_MINHUM_LEN_MIN            1

// Max humidity Characteristic defines
#define LS_MAXHUM_ID                 5
#define LS_MAXHUM_UUID               0x1156
#define LS_MAXHUM_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MAXHUM_LEN                3
#define LS_MAXHUM_LEN_MIN            1


// Min rain percentage Characteristic defines
#define LS_MINRAIN_ID                 6
#define LS_MINRAIN_UUID               0x1157
#define LS_MINRAIN_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_MINRAIN_LEN                3
#define LS_MINRAIN_LEN_MIN            1

// Current Temperature Characteristic defines
#define LS_CURTEMP_ID                 7
#define LS_CURTEMP_UUID               0x1158
#define LS_CURTEMP_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_CURTEMP_LEN                3
#define LS_CURTEMP_LEN_MIN            1

// Current Pressure Characteristic defines
#define LS_CURPRESS_ID                 8
#define LS_CURPRESS_UUID               0x1159
#define LS_CURPRESS_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_CURPRESS_LEN                3
#define LS_CURPRESS_LEN_MIN            1

// Current humidity Characteristic defines
#define LS_CURHUM_ID                 9
#define LS_CURHUM_UUID               0x115A
#define LS_CURHUM_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_CURHUM_LEN                3
#define LS_CURHUM_LEN_MIN            1


// Current rain percentage Characteristic defines
#define LS_CURRAIN_ID                 0xA
#define LS_CURRAIN_UUID               0x115B
#define LS_CURRAIN_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define LS_CURRAIN_LEN                3
#define LS_CURRAIN_LEN_MIN            1
*/

/*********************************************************************
 * TYPEDEFS
 */

// Fields in characteristic "LED0"
//   Field "Value" format: uint8, bits: 8

// Fields in characteristic "LED1"
//   Field "Value" format: uint8, bits: 8

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*ENVServiceChange_t)( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

typedef struct
{
  ENVServiceChange_t        pfnChangeCb;     // Called when characteristic value changes
  ENVServiceChange_t        pfnCfgChangeCb;  // Called when characteristic CCCD changes
} ENVServiceCBs_t;



/*********************************************************************
 * API FUNCTIONS
 */


/*
 * LedService_AddService- Initializes the LedService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t ENVService_AddService( uint8_t rspTaskId );

/*
 * LedService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t ENVService_RegisterAppCBs( ENVServiceCBs_t *appCallbacks );

/*
 * LedService_SetParameter - Set a LedService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t ENVService_SetParameter( uint8_t param, uint16_t len, void *value );

/*
 * LedService_GetParameter - Get a LedService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t ENVService_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/
//result value
extern uint8_t es_RESULTVal[ES_RESULT_LEN];


#ifdef __cplusplus
}
#endif

#endif /* _LED_SERVICE_H_ */
